name: Publish to PyPI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml

      - name: Read version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYSPACE2_TOKEN_2025 }}
        run: twine upload dist/* --verbose

      - name: Create Git tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
